spring:
  thymeleaf:
    cache: false
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: numberone
    password: 123456 
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:  
      hibernate:  
        dialect : org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    port: 6379
    pool: 
      max-active: 100